In [1]:
import numpy as np

In [2]:
# Function to perform Union operation on fuzzy sets
def fuzzy_union(A, B):
    return np.maximum(A, B)

In [3]:
# Function to perform Intersection operation on fuzzy sets
def fuzzy_intersection(A, B):
    return np.minimum(A, B)

In [4]:
# Function to perform Complement operation on a fuzzy set
def fuzzy_complement(A):
    return 1 - A

In [5]:
# Function to perform Difference operation on fuzzy sets
# A - B = A ∩ B'
def fuzzy_difference(A, B):
    return np.minimum(A, 1 - B)

In [6]:
# Function to create fuzzy relation by Cartesian product
# Uses minimum operator
def cartesian_product(A, B):
    return np.minimum.outer(A, B)

In [7]:
# Function to perform Max-Min Composition on two fuzzy relations
def max_min_composition(R, S):
    rows_R = R.shape[0]
    cols_S = S.shape[1]

    result = np.zeros((rows_R, cols_S))

    for i in range(rows_R):
        for j in range(cols_S):
            result[i, j] = np.max(np.minimum(R[i, :], S[:, j]))

    return result

In [8]:
# -----------------------------
# Example Fuzzy Sets
# -----------------------------
A = np.array([0.2, 0.4, 0.6, 0.8])
B = np.array([0.3, 0.5, 0.7, 0.9])


In [9]:
# Operations on fuzzy sets
union_result = fuzzy_union(A, B)
intersection_result = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
difference_result = fuzzy_difference(A, B)


In [10]:
# Display results
print("Fuzzy Set Operations")
print("---------------------")
print("A =", A)
print("B =", B)

Fuzzy Set Operations
---------------------
A = [0.2 0.4 0.6 0.8]
B = [0.3 0.5 0.7 0.9]


In [11]:
print("\nUnion of A and B:")
print(union_result)



Union of A and B:
[0.3 0.5 0.7 0.9]


In [12]:
print("\nIntersection of A and B:")
print(intersection_result)


Intersection of A and B:
[0.2 0.4 0.6 0.8]


In [13]:
print("\nComplement of A:")
print(complement_A)



Complement of A:
[0.8 0.6 0.4 0.2]


In [14]:
print("\nDifference of A and B (A - B):")
print(difference_result)


Difference of A and B (A - B):
[0.2 0.4 0.3 0.1]


In [15]:
# -----------------------------
# Cartesian Product
# -----------------------------
R_set = np.array([0.2, 0.5, 0.4])
S_set = np.array([0.6, 0.3, 0.7])

cartesian_result = cartesian_product(R_set, S_set)

print("\nCartesian Product of R and S:")
print(cartesian_result)


Cartesian Product of R and S:
[[0.2 0.2 0.2]
 [0.5 0.3 0.5]
 [0.4 0.3 0.4]]


In [16]:
# -----------------------------
# Max-Min Composition
# -----------------------------
# Define fuzzy relation matrices
R = np.array([
    [0.2, 0.5, 0.4],
    [0.7, 0.1, 0.6]
])

S = np.array([
    [0.9, 0.3],
    [0.5, 0.8],
    [0.6, 0.4]
])

composition_result = max_min_composition(R, S)

In [17]:
print("\nFuzzy Relation R:")
print(R)


Fuzzy Relation R:
[[0.2 0.5 0.4]
 [0.7 0.1 0.6]]


In [18]:
print("\nFuzzy Relation S:")
print(S)


Fuzzy Relation S:
[[0.9 0.3]
 [0.5 0.8]
 [0.6 0.4]]


In [19]:
print("\nMax-Min Composition of R and S:")
print(composition_result)


Max-Min Composition of R and S:
[[0.5 0.5]
 [0.7 0.4]]
